# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/11 14:26:55 by ksharlen          #+#    #+#              #
#    Updated: 2019/03/11 14:59:43 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = awesomeprog

SRC = source.c

all: $(NAME)

$(NAME):
	gcc -o$(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean:
	/bim/rm -f $(NAME)

re: fclean all
