# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/11 19:50:19 by marvin            #+#    #+#              #
#    Updated: 2019/06/11 19:50:19 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := ft_ls
CC := gcc
FLAGS := -g#-Wall -Werror -Wextra
MAIN := main.c
LIB := ./libft/libft.a

all:
	$(CC) $(FLAS) $(MAIN) -o $(NAME) $(LIB)

fclean:
	/bin/rm -f $(NAME)

re:	fclean all