# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <ksharlen@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/17 00:29:52 by ksharlen          #+#    #+#              #
#    Updated: 2019/06/19 10:20:28 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC := gcc
MAIN := main.c ft_input.c ft_malloc.c ft_output.c
OBJ := -o main

all:
	$(CC) $(MAIN) $(OBJ)

clean:
	/bin/rm -f

re: clean all