# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <ksharlen@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/10 13:17:42 by ksharlen          #+#    #+#              #
#    Updated: 2019/07/10 13:18:45 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -I ../ main.c src1.c src.c ../src/buf/buf.c ../src/buf/work_buf_by_hand.c libft.a

clean:
	@/bin/rm -f a.out

re: clean all