NAME := main
TESTING := ./testing_func/
FUNCTION := ft_test_functions_one.c
FLAGS := -Wextra -Wall -Werror
INCLUDES := ./includes

all:
	gcc $(FLAGS) -I $(INCLUDES) $(TESTING)$(FUNCTION) main.c -o $(NAME)


