# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/06 14:32:05 by ksharlen          #+#    #+#              #
#    Updated: 2019/04/07 13:35:46 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := main
FLAGS := -Wextra -Werror -Wall
INCLUDES := ./includes
SRCS := ./srcs/
FUNCTION := $(SRCS)ft_memset.c $(SRCS)ft_test_functions_one.c

all:
	gcc $(FLAGS) -I $(INCLUDES) main.c $(FUNCTION) -o $(NAME)

m:
	./main

clean:


fclean:


re:


