NAME := source
INCLUDES := ./includes
SRCS := ./srcs/srcs/
MAIN := ./srcs/main.c
FUNCTION := $(SRCS)ft_list.c $(SRCS)ft_input.c $(SRCS)ft_logic.c

all:
	@gcc $(MAIN) $(FUNCTION) -I $(INCLUDES) -L ./lib -lft -o $(NAME)

clean:
	@rm *.o

fclean:
	
